version: 0.0.0.{build}

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-Sonoma
      SCHEME: Moonlight
      SDK: iphonesimulator
      PLATFORM: iOS
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-Sonoma
      SCHEME: Moonlight TV
      SDK: appletvsimulator
      PLATFORM: tvOS

before_build:
  - 'git submodule update --init --recursive'
  - sh: 'xcodebuild -downloadPlatform $PLATFORM'

build_script:
  - sh: xcodebuild -project Moonlight.xcodeproj -scheme "$SCHEME" -configuration Debug -sdk $SDK clean build
  - sh: xcodebuild -project Moonlight.xcodeproj -scheme "$SCHEME" -configuration Release -sdk $SDK clean build

deploy: off
